language: "python"
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -U pytest
  - pip install -U pytest-runner
  - pip install -U coverage
  - pip install -U coveralls
script:
  - coverage run setup.py test
  - coveralls