language: "python"
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
services: mongodb
before_install:
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
env:
  - ENV=dev
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install -U pytest-runner
  - pip install -U psutil
  - pip install -U coverage
  - pip install -U coveralls
script:
  - coverage run setup.py test
  - coveralls