language: "python"
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -r dev-requirements.txt
  - pip install -U coverage
  - pip install -U coveralls
script:
  - coverage run setup.py test
  - coveralls